name: CD Pipeline

on:
  push:
    branches: [deploy]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name:  Checkout du code
        uses: actions/checkout@v3

      - name:  Rendre le script deploy.sh exécutable
        run: chmod +x ansible/deploy.sh

      - name:  Exécuter le script complet (Terraform + Ansible)
        run: ./deploy.sh
        working-directory: ansible
