name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout du code
        uses: actions/checkout@v3

      - name:  Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name:  Installer les dépendances
        run: npm install

      - name:  Lancer les tests unitaires
        run: npm test

  docker:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name:  Checkout du code
        uses: actions/checkout@v3

      - name:  Build de l’image Docker
        run: docker build -t la_manu_front .

      - name:  Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name:  Push sur Docker Hub
        run: |
          docker tag la_manu_front corentin382/la_manu_front-new:latest
          docker push corentin382/la_manu_front-new:latest
